backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "links"
    label: "Links"
    files:
      - label: "Links List"
        name: "links"
        file: "links.json"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
        format: json
